name: 'Hax'

on:
  workflow_dispatch:
  schedule:
    - cron: '36 14 */1 * *'
jobs:
  hax_renew:
    runs-on: windows-2022
    
    steps:
      - name: 'Hax VPS ....' 
        shell: cmd
        env:
          SECRET_USERNAME: ${{ secrets.USERNAME }}
          SECRET_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
         curl -sSL -O https://github.com/King-stark/Hax_extend/raw/main/HaxAutoReNew.exe
         HaxAutoReNew.exe -user "%SECRET_USERNAME%" -password "%SECRET_PASSWORD%"
